// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Sat Apr 06 14:26:14 2019

DCT1D DCT1D_inst
(
	.I_clk(I_clk_sig) ,	// input  I_clk_sig
	.I_rst_n(I_rst_n_sig) ,	// input  I_rst_n_sig
	.I_en(I_en_sig) ,	// input  I_en_sig
	.I_valid_data(I_valid_data_sig) ,	// input  I_valid_data_sig
	.I_data(I_data_sig) ,	// input [7:0] I_data_sig
	.O_f0(O_f0_sig) ,	// output [15:0] O_f0_sig
	.O_f1(O_f1_sig) ,	// output [15:0] O_f1_sig
	.O_f2(O_f2_sig) ,	// output [15:0] O_f2_sig
	.O_f3(O_f3_sig) ,	// output [15:0] O_f3_sig
	.O_f4(O_f4_sig) ,	// output [15:0] O_f4_sig
	.O_f5(O_f5_sig) ,	// output [15:0] O_f5_sig
	.O_f6(O_f6_sig) ,	// output [15:0] O_f6_sig
	.O_f7(O_f7_sig) ,	// output [15:0] O_f7_sig
	.O_data_ready(O_data_ready_sig) ,	// output  O_data_ready_sig
	.O_data_valid(O_data_valid_sig) 	// output  O_data_valid_sig
);

