// Copyright (C) 2017  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 17.1 (Build Build 590 10/25/2017)
// Created on Sat Apr 06 16:41:10 2019

Parallel2Series Parallel2Series_inst
(
	.I_clk(I_clk_sig) ,	// input  I_clk_sig
	.I_rst_n(I_rst_n_sig) ,	// input  I_rst_n_sig
	.I_en(I_en_sig) ,	// input  I_en_sig
	.I_push(I_push_sig) ,	// input  I_push_sig
	.I_d0(I_d0_sig) ,	// input [DATA_WIDTH-1:0] I_d0_sig
	.I_d1(I_d1_sig) ,	// input [DATA_WIDTH-1:0] I_d1_sig
	.I_d2(I_d2_sig) ,	// input [DATA_WIDTH-1:0] I_d2_sig
	.I_d3(I_d3_sig) ,	// input [DATA_WIDTH-1:0] I_d3_sig
	.I_d4(I_d4_sig) ,	// input [DATA_WIDTH-1:0] I_d4_sig
	.I_d5(I_d5_sig) ,	// input [DATA_WIDTH-1:0] I_d5_sig
	.I_d6(I_d6_sig) ,	// input [DATA_WIDTH-1:0] I_d6_sig
	.I_d7(I_d7_sig) ,	// input [DATA_WIDTH-1:0] I_d7_sig
	.O_q(O_q_sig) ,	// output [DATA_WIDTH-1:0] O_q_sig
	.O_data_valid(O_data_valid_sig) ,	// output  O_data_valid_sig
	.data_left(data_left_sig) 	// output [2:0] data_left_sig
);

defparam Parallel2Series_inst.DATA_WIDTH = 8;
